name: Greg@GregMuffler.com
favicon: null
layout_spectrum: 0.11134712910279632
typography_spectrum: 0.6842585606500506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6c95bf'
    - '#fd981f'
    - '#b3cf27'
    - '#c4d5e6'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
